# Generated by Django 4.1.2 on 2022-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=200)),
                ('anio_estreno', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('clasificacion_edad', models.IntegerField()),
            ],
        ),
    ]
