# Generated by Django 4.1.2 on 2022-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pelicula_imagen_alter_pelicula_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fe_alta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fe_cambio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
