# Generated by Django 4.1.2 on 2022-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pelicula_fe_alta_pelicula_fe_cambio_pelicula_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fe_alta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fe_cambio',
            field=models.DateTimeField(null=True),
        ),
    ]
