# Generated by Django 4.1.2 on 2022-11-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_pelicula_fe_alta_alter_pelicula_fe_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
